name: CI/CD pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "ap-south-1"
      S3_BUCKET: "dev-ops-bkt"
      S3_KEY: "lambda_package.zip"
      LAMBDA_FUNCTION_NAME: "LambdaFunctionOverHttps"
      IAM_ROLE_NAME: "arn:aws:iam::597727830496:role/lambda-apigateway-role"


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.14'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      
      - name: Zip files
        run: |
          rm -f lambda_package.zip
          zip lambda_package.zip lambda_handler.py

      - name: AWS configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deploy to S3
        run: aws s3 cp lambda_package.zip s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }}

      - name: Update/Create Lambda function
        run: |
          aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} && \
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET }} --s3-key ${{ env.S3_KEY }} || \
          aws lambda create-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --runtime python3.14 \
            --role ${{ env.IAM_ROLE_NAME }} \
            --handler lambda_handler.lambda_handler \
            --code S3Bucket=${{ env.S3_BUCKET }},S3Key=${{ env.S3_KEY }} \
            --timeout 20 \
            --memory-size 128

